<?php
/**
 * Offair drop-in.
 *
 * WordPress loads this file by itself, before any plugin or theme, in three
 * situations: when the database is unreachable (wp-content/db-error.php),
 * while it installs updates (wp-content/maintenance.php) and after a fatal
 * PHP error (wp-content/php-error.php). WordPress functions are not
 * available at that point, so this file only uses plain PHP.
 *
 * The Offair plugin copies this file unchanged under those
 * three names. The page content comes from the JSON file the plugin saves in
 * the uploads folder (offair/pages.json). When that file is
 * missing, a neutral English page is shown instead.
 *
 * Do not edit this file: the plugin replaces it when it is updated and
 * removes it when it is deactivated or uninstalled.
 *
 * @package Offair
 */

defined( 'ABSPATH' ) || exit;

/*
 * Everything runs inside a closure so that no global variable or function is
 * declared. WordPress includes this file from inside one of its own functions,
 * and php-error.php receives $error and $handled from that scope.
 */
( static function ( $error, $handled ) {
	$screens = array(
		'db-error.php'    => 'db',
		'maintenance.php' => 'maintenance',
		'php-error.php'   => 'php',
	);
	$file    = basename( __FILE__ );
	$screen  = isset( $screens[ $file ] ) ? $screens[ $file ] : 'db';

	// The plugin preview and WP-CLI render a given page from the plugin folder.
	if ( defined( 'OFFAIR_PREVIEW' ) && in_array( OFFAIR_PREVIEW, $screens, true ) ) {
		$screen = OFFAIR_PREVIEW;
	}

	$esc = static function ( $value ) {
		return htmlspecialchars( (string) $value, ENT_QUOTES, 'UTF-8' );
	};
	$str = static function ( $value, $fallback = '' ) {
		return is_string( $value ) ? $value : $fallback;
	};
	$num = static function ( $value, $min, $max, $fallback ) {
		return is_int( $value ) && $value >= $min && $value <= $max ? $value : $fallback;
	};
	$hex = static function ( $value, $fallback ) {
		return is_string( $value ) && preg_match( '/^#[0-9a-f]{6}$/i', $value ) ? strtolower( $value ) : $fallback;
	};

	// Neutral page used when the plugin data cannot be read.
	$fallback_screens = array(
		'db'          => array(
			'title'      => "We'll be right back",
			'paragraphs' => array( 'Our site is taking a short break because of a technical problem. It usually comes back within a few minutes.' ),
			'meta'       => 'Incident recorded at {time} (UTC). Database temporarily unavailable (HTTP 503).',
		),
		'maintenance' => array(
			'title'      => 'Back in a minute',
			'paragraphs' => array( 'We are installing an update. The site will be back in a moment.' ),
			'meta'       => 'Incident recorded at {time} (UTC). Scheduled maintenance in progress (HTTP 503).',
		),
		'php'         => array(
			'title'      => 'Something went wrong',
			'paragraphs' => array( 'A technical error prevents us from displaying this page right now. Please try again in a few minutes.' ),
			'meta'       => 'Incident recorded at {time} (UTC). Technical error (HTTP 503).',
		),
	);
	$page_defaults    = array(
		'button'      => 'Try again',
		'refresh'     => 60,
		'retry_after' => 300,
		'status'      => 503,
		'notice'      => '',
	);

	/*
	 * Same location as wp_upload_dir() for the main site. The database may be
	 * down, so the path is worked out from the constants WordPress defines in
	 * wp-config.php and wp-settings.php.
	 */
	$content_dir = defined( 'WP_CONTENT_DIR' ) ? WP_CONTENT_DIR : ABSPATH . 'wp-content';
	$uploads_dir = defined( 'UPLOADS' ) ? ABSPATH . UPLOADS : $content_dir . '/uploads';
	$data_file   = rtrim( $uploads_dir, '/\\' ) . '/offair/pages.json';
	$data        = array();

	if ( is_readable( $data_file ) ) {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local file, WordPress is not loaded.
		$raw  = file_get_contents( $data_file );
		$json = is_string( $raw ) ? json_decode( $raw, true ) : null;
		$data = is_array( $json ) ? $json : array();
	}

	$page = array_merge( $page_defaults, $fallback_screens[ $screen ] );
	if ( isset( $data['screens'][ $screen ] ) && is_array( $data['screens'][ $screen ] ) ) {
		$page = array_merge( $page, $data['screens'][ $screen ] );
	}

	$status      = 500 === $num( $page['status'], 500, 503, 503 ) ? 500 : 503;
	$retry_after = $num( $page['retry_after'], 0, 86400, 300 );
	$refresh     = $num( $page['refresh'], 0, 3600, 60 );

	// A fatal error may leave partial output behind: start from a clean page.
	if ( 'php' === $screen ) {
		while ( ob_get_level() > 0 && ob_end_clean() ) {
			continue;
		}
	}

	if ( ! headers_sent() ) {
		// Same status line as WordPress builds in status_header(), from a fixed list of protocols.
		$protocols = array( 'HTTP/1.1', 'HTTP/2', 'HTTP/2.0', 'HTTP/3' );
		$protocol  = isset( $_SERVER['SERVER_PROTOCOL'] ) && in_array( $_SERVER['SERVER_PROTOCOL'], $protocols, true ) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.0'; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- Compared against a fixed list, WordPress is not loaded.
		header( $protocol . ' ' . ( 503 === $status ? '503 Service Unavailable' : '500 Internal Server Error' ), true, $status );
		if ( 503 === $status && $retry_after > 0 ) {
			header( 'Retry-After: ' . $retry_after );
		}
		header( 'Content-Type: text/html; charset=UTF-8' );
		header( 'Cache-Control: no-store, no-cache, must-revalidate, max-age=0' );
		header( 'Pragma: no-cache' );
		header( 'Expires: Wed, 11 Jan 1984 05:00:00 GMT' );
		header( 'X-LiteSpeed-Cache-Control: no-cache' );
		header( 'X-Robots-Tag: noindex, nofollow' );
	}

	// Local time of the incident, in the timezone of the site.
	$time = gmdate( 'H:i' ) . ' UTC';
	try {
		$now  = new DateTime( 'now', new DateTimeZone( $str( isset( $data['timezone'] ) ? $data['timezone'] : null, 'UTC' ) ) );
		$time = $now->format( $str( isset( $data['time_format'] ) ? $data['time_format'] : null, 'H:i' ) );
	} catch ( Exception $exception ) {
		$time = gmdate( 'H:i' ) . ' UTC';
	}

	// Technical details, only where WordPress itself would print errors.
	$detail = '';
	if ( 'php' === $screen && defined( 'WP_DEBUG' ) && WP_DEBUG && defined( 'WP_DEBUG_DISPLAY' ) && WP_DEBUG_DISPLAY && is_array( $error ) ) {
		$detail = trim( $str( isset( $error['message'] ) ? $error['message'] : null ) );
		if ( isset( $error['file'] ) ) {
			$detail .= "\n" . $str( $error['file'] ) . ( isset( $error['line'] ) ? ':' . (int) $error['line'] : '' );
		}
		$detail = trim( $detail );
	}

	// An administrator in recovery mode is told what just happened.
	$notice = '';
	if ( 'php' === $screen && true === $handled && function_exists( 'wp_is_recovery_mode' ) && wp_is_recovery_mode() ) {
		$notice = $str( $page['notice'] );
	}

	$colors     = isset( $data['colors'] ) && is_array( $data['colors'] ) ? $data['colors'] : array();
	$primary    = $hex( isset( $colors['primary'] ) ? $colors['primary'] : null, '#334155' );
	$hover      = $hex( isset( $colors['primary_hover'] ) ? $colors['primary_hover'] : null, $primary );
	$text_color = $hex( isset( $colors['primary_text'] ) ? $colors['primary_text'] : null, $primary );
	$on_primary = $hex( isset( $colors['on_primary'] ) ? $colors['on_primary'] : null, '#ffffff' );
	$background = $hex( isset( $colors['background'] ) ? $colors['background'] : null, '#f5f4f0' );
	$rgb        = sscanf( $primary, '#%02x%02x%02x' );
	$shadow     = sprintf( 'rgba(%d, %d, %d, 0.12)', $rgb[0], $rgb[1], $rgb[2] );

	$lang      = $str( isset( $data['lang'] ) ? $data['lang'] : null, 'en' );
	$lang      = preg_match( '/^[a-z]{2,3}(-[a-z0-9]{2,8})*$/i', $lang ) ? $lang : 'en';
	$site_name = $str( isset( $data['site_name'] ) ? $data['site_name'] : null );
	$show_name = ! empty( $data['show_name'] ) && '' !== $site_name;
	$font      = isset( $data['heading_font'] ) && 'sans' === $data['heading_font'] ? 'sans' : 'serif';
	$ornament  = isset( $data['ornament'] ) && in_array( $data['ornament'], array( 'wave', 'line', 'none' ), true ) ? $data['ornament'] : 'line';
	$title     = $str( $page['title'] );
	$button    = $str( $page['button'] );
	$meta      = str_replace( '{time}', $time, $str( $page['meta'] ) );
	$image     = '#^data:image/(?:png|jpeg|gif|webp|svg\+xml|x-icon|vnd\.microsoft\.icon);base64,[a-z0-9+/=]+$#i';

	$logo = '';
	if ( isset( $data['logo']['src'] ) && is_string( $data['logo']['src'] ) && preg_match( $image, $data['logo']['src'] ) ) {
		$width  = $num( isset( $data['logo']['width'] ) ? $data['logo']['width'] : null, 1, 2000, 0 );
		$height = $num( isset( $data['logo']['height'] ) ? $data['logo']['height'] : null, 1, 2000, 0 );
		$size   = $width && $height ? ' width="' . $width . '" height="' . $height . '"' : '';
		$logo   = '<img class="offair-logo" src="' . $esc( $data['logo']['src'] ) . '" alt="' . $esc( $site_name ) . '"' . $size . '>';
	}

	$favicon = '';
	if ( isset( $data['favicon'] ) && is_string( $data['favicon'] ) && preg_match( $image, $data['favicon'] ) ) {
		$favicon = '<link rel="icon" href="' . $esc( $data['favicon'] ) . '">';
	}

	$paragraphs = '';
	foreach ( is_array( $page['paragraphs'] ) ? $page['paragraphs'] : array() as $paragraph ) {
		if ( is_string( $paragraph ) && '' !== trim( $paragraph ) ) {
			$paragraphs .= '<p>' . nl2br( $esc( trim( $paragraph ) ) ) . '</p>';
		}
	}

	$contact = '';
	foreach ( isset( $data['contact'] ) && is_array( $data['contact'] ) ? $data['contact'] : array() as $part ) {
		if ( ! isset( $part['text'] ) || ! is_string( $part['text'] ) ) {
			continue;
		}
		if ( isset( $part['href'] ) && is_string( $part['href'] ) && preg_match( '#^(?:https?://|mailto:)#i', $part['href'] ) ) {
			$contact .= '<a href="' . $esc( $part['href'] ) . '">' . $esc( $part['text'] ) . '</a>';
		} else {
			$contact .= $esc( $part['text'] );
		}
	}

	$ornaments = array(
		'wave' => '<svg class="offair-ornament offair-ornament-wave" viewBox="0 0 72 14" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M2 8c6-8 12-8 18 0s12 8 18 0 12-8 18 0 12 8 14 0"/></svg>',
		'line' => '<span class="offair-ornament offair-ornament-line" aria-hidden="true"></span>',
		'none' => '',
	);

	/*
	 * Styles are printed inline on purpose: this page is shown while
	 * WordPress cannot load, and during updates, when the plugin folder may
	 * be in the middle of being replaced. A stylesheet could not be enqueued
	 * and a link to one could return an error.
	 */
	$css = <<<'CSS'
:root{--offair-primary:%primary%;--offair-primary-hover:%hover%;--offair-primary-text:%text%;--offair-on-primary:%on%;--offair-background:%background%;--offair-shadow:%shadow%}
*,*::before,*::after{box-sizing:border-box}
html,body{margin:0;padding:0;min-height:100%}
body{font-family:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;color:#555;background-color:var(--offair-background);background-image:linear-gradient(180deg,rgba(255,255,255,.85) 0%,rgba(255,255,255,0) 100%);display:flex;align-items:center;justify-content:center;min-height:100vh;padding:24px 16px;line-height:1.6;-webkit-font-smoothing:antialiased}
.offair-font-serif .offair-brand,.offair-font-serif .offair-title{font-family:Georgia,"Iowan Old Style","Palatino Linotype",Palatino,"Book Antiqua","Times New Roman",serif}
.offair-font-sans .offair-brand,.offair-font-sans .offair-title{font-family:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif}
.offair-card{background:#fff;max-width:520px;width:100%;padding:48px 32px 36px;border-radius:16px;box-shadow:0 12px 40px var(--offair-shadow);text-align:center}
.offair-logo{display:block;margin:0 auto 20px;width:auto;height:auto;max-width:160px;max-height:120px}
.offair-brand{font-size:15px;letter-spacing:.18em;text-transform:uppercase;color:var(--offair-primary-text);margin:0 0 24px}
.offair-ornament{display:block;margin:0 auto 24px;color:var(--offair-primary-text)}
.offair-ornament-wave{width:72px;height:14px}
.offair-ornament-line{width:40px;height:2px;background:var(--offair-primary-text);border-radius:2px}
.offair-title{font-weight:600;font-size:26px;line-height:1.3;color:#222;margin:0 0 16px}
.offair-message p{margin:0 0 14px;font-size:16px}
.offair-button{display:inline-block;margin:18px 0 8px;padding:12px 28px;background:var(--offair-primary);color:var(--offair-on-primary);text-decoration:none;border-radius:999px;font-size:15px;letter-spacing:.04em;transition:background .15s ease}
.offair-button:hover,.offair-button:focus{background:var(--offair-primary-hover)}
.offair-button:focus-visible{outline:2px solid var(--offair-primary-text);outline-offset:3px}
.offair-contact{font-size:14px;color:#777;margin:12px 0 0}
.offair-contact a{color:var(--offair-primary-text)}
.offair-meta{font-size:13px;color:#999;margin:20px 0 0}
.offair-notice{font-size:14px;color:#7a4f00;background:#fff6dd;border-radius:8px;padding:10px 14px;margin:20px 0 0;text-align:left}
.offair-detail{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:1.5;color:#333;background:#f4f4f4;border-radius:8px;padding:12px 14px;margin:20px 0 0;text-align:left;white-space:pre-wrap;word-break:break-word}
@media (max-width:420px){.offair-card{padding:36px 20px 28px}.offair-title{font-size:22px}}
CSS;
	$css = strtr(
		$css,
		array(
			'%primary%'    => $primary,
			'%hover%'      => $hover,
			'%text%'       => $text_color,
			'%on%'         => $on_primary,
			'%background%' => $background,
			'%shadow%'     => $shadow,
		)
	);

	$html   = array();
	$html[] = '<!DOCTYPE html>';
	$html[] = '<html lang="' . $esc( $lang ) . '">';
	$html[] = '<head>';
	$html[] = '<meta charset="UTF-8">';
	$html[] = '<meta name="viewport" content="width=device-width, initial-scale=1">';
	$html[] = '<meta name="robots" content="noindex, nofollow">';
	$html[] = $refresh > 0 ? '<meta http-equiv="refresh" content="' . $refresh . '">' : '';
	$html[] = '<title>' . $esc( '' !== $site_name ? $title . ' · ' . $site_name : $title ) . '</title>';
	$html[] = $favicon;
	$html[] = '<style>' . $css . '</style>';
	$html[] = '</head>';
	$html[] = '<body class="offair-font-' . $font . ' offair-screen-' . $screen . '">';
	$html[] = '<main class="offair-card">';
	$html[] = $logo;
	$html[] = $show_name ? '<p class="offair-brand">' . $esc( $site_name ) . '</p>' : '';
	$html[] = $ornaments[ $ornament ];
	$html[] = '<h1 class="offair-title">' . $esc( $title ) . '</h1>';
	$html[] = '' !== $paragraphs ? '<div class="offair-message">' . $paragraphs . '</div>' : '';
	$html[] = '' !== $button ? '<a class="offair-button" href="">' . $esc( $button ) . '</a>' : '';
	$html[] = '' !== $contact ? '<p class="offair-contact">' . $contact . '</p>' : '';
	$html[] = '' !== $notice ? '<p class="offair-notice">' . $esc( $notice ) . '</p>' : '';
	$html[] = '' !== $detail ? '<pre class="offair-detail">' . $esc( $detail ) . '</pre>' : '';
	$html[] = '' !== $meta ? '<p class="offair-meta">' . $esc( $meta ) . '</p>' : '';
	$html[] = '</main>';
	$html[] = '</body>';
	$html[] = '</html>';

	// Every value above was escaped with htmlspecialchars(): WordPress escaping functions are not loaded here.
	echo implode( "\n", array_filter( $html, 'strlen' ) ) . "\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
} )( isset( $error ) ? $error : null, isset( $handled ) ? $handled : null );
