<?php
/**
 * Offair drop-in.
 *
 * WordPress loads this file by itself, before any plugin or theme, in three
 * situations: when the database is unreachable (wp-content/db-error.php),
 * while it installs updates (wp-content/maintenance.php) and after a fatal
 * PHP error (wp-content/php-error.php). WordPress functions are not
 * available at that point, so this file only uses plain PHP.
 *
 * The Offair plugin copies this file unchanged under those
 * three names. The page content comes from the JSON file the plugin saves in
 * the uploads folder (offair/pages.json). When that file is
 * missing, a neutral English page is shown instead.
 *
 * Do not edit this file: the plugin replaces it when it is updated and
 * removes it when it is deactivated or uninstalled.
 *
 * @package Offair
 */

defined( 'ABSPATH' ) || exit;

/*
 * Everything runs inside a closure so that no global variable or function is
 * declared. WordPress includes this file from inside one of its own functions,
 * and php-error.php receives $error and $handled from that scope.
 */
( static function ( $error, $handled ) {
	$screens = array(
		'db-error.php'    => 'db',
		'maintenance.php' => 'maintenance',
		'php-error.php'   => 'php',
	);
	$file    = basename( __FILE__ );
	$screen  = isset( $screens[ $file ] ) ? $screens[ $file ] : 'db';

	// The plugin preview and WP-CLI render a given page from the plugin folder.
	if ( defined( 'OFFAIR_PREVIEW' ) && in_array( OFFAIR_PREVIEW, $screens, true ) ) {
		$screen = OFFAIR_PREVIEW;
	}

	$esc = static function ( $value ) {
		return htmlspecialchars( (string) $value, ENT_QUOTES, 'UTF-8' );
	};
	$str = static function ( $value, $fallback = '' ) {
		return is_string( $value ) ? $value : $fallback;
	};
	$num = static function ( $value, $min, $max, $fallback ) {
		return is_int( $value ) && $value >= $min && $value <= $max ? $value : $fallback;
	};
	$hex = static function ( $value, $fallback ) {
		return is_string( $value ) && preg_match( '/^#[0-9a-f]{6}$/i', $value ) ? strtolower( $value ) : $fallback;
	};

	// Neutral page used when the plugin data cannot be read.
	$fallback_screens = array(
		'db'          => array(
			'title'      => "We'll be right back",
			'paragraphs' => array( 'Our site is taking a short break because of a technical problem. It usually comes back within a few minutes.' ),
			'meta'       => 'Incident recorded at {time} (UTC). Database temporarily unavailable (HTTP 503).',
		),
		'maintenance' => array(
			'title'      => 'Back in a minute',
			'paragraphs' => array( 'We are installing an update. The site will be back in a moment.' ),
			'meta'       => 'Incident recorded at {time} (UTC). Scheduled maintenance in progress (HTTP 503).',
		),
		'php'         => array(
			'title'      => 'Something went wrong',
			'paragraphs' => array( 'A technical error prevents us from displaying this page right now. Please try again in a few minutes.' ),
			'meta'       => 'Incident recorded at {time} (UTC). Technical error (HTTP 503).',
			'refresh'    => 0,
		),
	);
	$page_defaults    = array(
		'button'      => 'Try again',
		'refresh'     => 60,
		'retry_after' => 300,
		'status'      => 503,
		'notice'      => '',
	);

	/*
	 * Same location as wp_upload_dir() for the main site. The database may be
	 * down, so the path is worked out from the constants WordPress defines in
	 * wp-config.php and wp-settings.php.
	 */
	$content_dir = defined( 'WP_CONTENT_DIR' ) ? WP_CONTENT_DIR : ABSPATH . 'wp-content';
	$uploads_dir = defined( 'UPLOADS' ) ? ABSPATH . UPLOADS : $content_dir . '/uploads';
	$data_file   = rtrim( $uploads_dir, '/\\' ) . '/offair/pages.json';
	$data        = array();

	if ( is_readable( $data_file ) ) {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local file, WordPress is not loaded.
		$raw  = file_get_contents( $data_file );
		$json = is_string( $raw ) ? json_decode( $raw, true ) : null;
		$data = is_array( $json ) ? $json : array();
	}

	/*
	 * Private folder, next to the data file: its name cannot be guessed, so
	 * it is found by its prefix. It holds the alert settings, the folders of
	 * the active theme and the history of the pages shown.
	 */
	$private_dir = '';
	$private     = array();
	$found       = glob( dirname( $data_file ) . '/private-*', defined( 'GLOB_ONLYDIR' ) ? GLOB_ONLYDIR : 0 );

	if ( is_array( $found ) && isset( $found[0] ) && is_dir( $found[0] ) ) {
		$private_dir = $found[0];

		if ( is_readable( $private_dir . '/private.json' ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local file, WordPress is not loaded.
			$raw     = file_get_contents( $private_dir . '/private.json' );
			$json    = is_string( $raw ) ? json_decode( $raw, true ) : null;
			$private = is_array( $json ) ? $json : array();
		}
	}

	/*
	 * A template named after this file, in an offair folder of the active
	 * theme or of its parent, replaces the built-in page. The path is checked
	 * against wp-content/themes, never against the data files, which sit in a
	 * folder the web server can write to.
	 */
	$template = '';
	$themes   = realpath( $content_dir . '/themes' );
	$files    = array_flip( $screens );

	foreach ( false !== $themes && isset( $private['themes'] ) && is_array( $private['themes'] ) ? $private['themes'] : array() as $theme_dir ) {
		$candidate = is_string( $theme_dir ) ? realpath( $theme_dir . '/offair/' . $files[ $screen ] ) : false;

		if ( false !== $candidate && 0 === strpos( $candidate, $themes . DIRECTORY_SEPARATOR ) && is_readable( $candidate ) ) {
			$template = $candidate;
			break;
		}
	}

	$page = array_merge( $page_defaults, $fallback_screens[ $screen ] );
	if ( isset( $data['screens'][ $screen ] ) && is_array( $data['screens'][ $screen ] ) ) {
		$page = array_merge( $page, $data['screens'][ $screen ] );
	}

	$status      = 500 === $num( $page['status'], 500, 503, 503 ) ? 500 : 503;
	$retry_after = $num( $page['retry_after'], 0, 86400, 300 );
	$refresh     = $num( $page['refresh'], 0, 3600, 60 );

	// A fatal error may leave partial output behind: start from a clean page.
	if ( 'php' === $screen ) {
		while ( ob_get_level() > 0 && ob_end_clean() ) {
			continue;
		}
	}

	if ( ! headers_sent() ) {
		// Same status line as WordPress builds in status_header(), from a fixed list of protocols.
		$protocols = array( 'HTTP/1.1', 'HTTP/2', 'HTTP/2.0', 'HTTP/3' );
		$protocol  = isset( $_SERVER['SERVER_PROTOCOL'] ) && in_array( $_SERVER['SERVER_PROTOCOL'], $protocols, true ) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.0'; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- Compared against a fixed list, WordPress is not loaded.
		header( $protocol . ' ' . ( 503 === $status ? '503 Service Unavailable' : '500 Internal Server Error' ), true, $status );
		if ( 503 === $status && $retry_after > 0 ) {
			header( 'Retry-After: ' . $retry_after );
		}
		header( 'Content-Type: text/html; charset=UTF-8' );
		header( 'Cache-Control: no-store, no-cache, must-revalidate, max-age=0' );
		header( 'Pragma: no-cache' );
		header( 'Expires: Wed, 11 Jan 1984 05:00:00 GMT' );
		header( 'X-LiteSpeed-Cache-Control: no-cache' );
		header( 'X-Robots-Tag: noindex, nofollow' );
	}

	// Local time of the incident, in the timezone of the site.
	$time = gmdate( 'H:i' ) . ' UTC';
	try {
		$now  = new DateTime( 'now', new DateTimeZone( $str( isset( $data['timezone'] ) ? $data['timezone'] : null, 'UTC' ) ) );
		$time = $now->format( $str( isset( $data['time_format'] ) ? $data['time_format'] : null, 'H:i' ) );
	} catch ( Exception $exception ) {
		$time = gmdate( 'H:i' ) . ' UTC';
	}

	// Technical details, only where WordPress itself would print errors.
	$detail = '';
	if ( 'php' === $screen && defined( 'WP_DEBUG' ) && WP_DEBUG && defined( 'WP_DEBUG_DISPLAY' ) && WP_DEBUG_DISPLAY && is_array( $error ) ) {
		$detail = trim( $str( isset( $error['message'] ) ? $error['message'] : null ) );
		if ( isset( $error['file'] ) ) {
			$detail .= "\n" . $str( $error['file'] ) . ( isset( $error['line'] ) ? ':' . (int) $error['line'] : '' );
		}
		$detail = trim( $detail );
	}

	// An administrator in recovery mode is told what just happened.
	$notice = '';
	if ( 'php' === $screen && true === $handled && function_exists( 'wp_is_recovery_mode' ) && wp_is_recovery_mode() ) {
		$notice = $str( $page['notice'] );
	}

	$colors     = isset( $data['colors'] ) && is_array( $data['colors'] ) ? $data['colors'] : array();
	$primary    = $hex( isset( $colors['primary'] ) ? $colors['primary'] : null, '#334155' );
	$hover      = $hex( isset( $colors['primary_hover'] ) ? $colors['primary_hover'] : null, $primary );
	$text_color = $hex( isset( $colors['primary_text'] ) ? $colors['primary_text'] : null, $primary );
	$on_primary = $hex( isset( $colors['on_primary'] ) ? $colors['on_primary'] : null, '#ffffff' );
	$background = $hex( isset( $colors['background'] ) ? $colors['background'] : null, '#f5f4f0' );
	$rgb        = sscanf( $primary, '#%02x%02x%02x' );
	$shadow     = sprintf( 'rgba(%d, %d, %d, 0.12)', $rgb[0], $rgb[1], $rgb[2] );

	$lang      = $str( isset( $data['lang'] ) ? $data['lang'] : null, 'en' );
	$lang      = preg_match( '/^[a-z]{2,3}(-[a-z0-9]{2,8})*$/i', $lang ) ? $lang : 'en';
	$site_name = $str( isset( $data['site_name'] ) ? $data['site_name'] : null );
	$show_name = ! empty( $data['show_name'] ) && '' !== $site_name;
	$font      = isset( $data['heading_font'] ) && 'sans' === $data['heading_font'] ? 'sans' : 'serif';
	$ornament  = isset( $data['ornament'] ) && in_array( $data['ornament'], array( 'wave', 'line', 'none' ), true ) ? $data['ornament'] : 'line';
	$title     = $str( $page['title'] );
	$button    = $str( $page['button'] );
	$meta      = str_replace( '{time}', $time, $str( $page['meta'] ) );
	$image     = '#^data:image/(?:png|jpeg|gif|webp|svg\+xml|x-icon|vnd\.microsoft\.icon);base64,[a-z0-9+/=]+$#i';

	$logo      = '';
	$logo_data = null;
	if ( isset( $data['logo']['src'] ) && is_string( $data['logo']['src'] ) && preg_match( $image, $data['logo']['src'] ) ) {
		$width     = $num( isset( $data['logo']['width'] ) ? $data['logo']['width'] : null, 1, 2000, 0 );
		$height    = $num( isset( $data['logo']['height'] ) ? $data['logo']['height'] : null, 1, 2000, 0 );
		$size      = $width && $height ? ' width="' . $width . '" height="' . $height . '"' : '';
		$logo      = '<img class="offair-logo" src="' . $esc( $data['logo']['src'] ) . '" alt="' . $esc( $site_name ) . '"' . $size . '>';
		$logo_data = array(
			'src'    => $data['logo']['src'],
			'width'  => $width,
			'height' => $height,
		);
	}

	$favicon      = '';
	$favicon_data = '';
	if ( isset( $data['favicon'] ) && is_string( $data['favicon'] ) && preg_match( $image, $data['favicon'] ) ) {
		$favicon      = '<link rel="icon" href="' . $esc( $data['favicon'] ) . '">';
		$favicon_data = $data['favicon'];
	}

	$paragraphs     = '';
	$paragraph_list = array();
	foreach ( is_array( $page['paragraphs'] ) ? $page['paragraphs'] : array() as $paragraph ) {
		if ( is_string( $paragraph ) && '' !== trim( $paragraph ) ) {
			$paragraphs      .= '<p>' . nl2br( $esc( trim( $paragraph ) ) ) . '</p>';
			$paragraph_list[] = trim( $paragraph );
		}
	}

	$contact       = '';
	$contact_parts = array();
	foreach ( isset( $data['contact'] ) && is_array( $data['contact'] ) ? $data['contact'] : array() as $part ) {
		if ( ! isset( $part['text'] ) || ! is_string( $part['text'] ) ) {
			continue;
		}
		if ( isset( $part['href'] ) && is_string( $part['href'] ) && preg_match( '#^(?:https?://|mailto:)#i', $part['href'] ) ) {
			$contact        .= '<a href="' . $esc( $part['href'] ) . '">' . $esc( $part['text'] ) . '</a>';
			$contact_parts[] = array(
				'text' => $part['text'],
				'href' => $part['href'],
			);
		} else {
			$contact        .= $esc( $part['text'] );
			$contact_parts[] = array( 'text' => $part['text'] );
		}
	}

	$ornaments = array(
		'wave' => '<svg class="offair-ornament offair-ornament-wave" viewBox="0 0 72 14" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M2 8c6-8 12-8 18 0s12 8 18 0 12-8 18 0 12 8 14 0"/></svg>',
		'line' => '<span class="offair-ornament offair-ornament-line" aria-hidden="true"></span>',
		'none' => '',
	);

	/*
	 * Styles are printed inline on purpose: this page is shown while
	 * WordPress cannot load, and during updates, when the plugin folder may
	 * be in the middle of being replaced. A stylesheet could not be enqueued
	 * and a link to one could return an error.
	 */
	$css = <<<'CSS'
:root{--offair-primary:%primary%;--offair-primary-hover:%hover%;--offair-primary-text:%text%;--offair-on-primary:%on%;--offair-background:%background%;--offair-shadow:%shadow%}
*,*::before,*::after{box-sizing:border-box}
html,body{margin:0;padding:0;min-height:100%}
body{font-family:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;color:#555;background-color:var(--offair-background);background-image:linear-gradient(180deg,rgba(255,255,255,.85) 0%,rgba(255,255,255,0) 100%);display:flex;align-items:center;justify-content:center;min-height:100vh;padding:24px 16px;line-height:1.6;-webkit-font-smoothing:antialiased}
.offair-font-serif .offair-brand,.offair-font-serif .offair-title{font-family:Georgia,"Iowan Old Style","Palatino Linotype",Palatino,"Book Antiqua","Times New Roman",serif}
.offair-font-sans .offair-brand,.offair-font-sans .offair-title{font-family:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif}
.offair-card{background:#fff;max-width:520px;width:100%;padding:48px 32px 36px;border-radius:16px;box-shadow:0 12px 40px var(--offair-shadow);text-align:center}
.offair-logo{display:block;margin:0 auto 20px;width:auto;height:auto;max-width:160px;max-height:120px}
.offair-brand{font-size:15px;letter-spacing:.18em;text-transform:uppercase;color:var(--offair-primary-text);margin:0 0 24px}
.offair-ornament{display:block;margin:0 auto 24px;color:var(--offair-primary-text)}
.offair-ornament-wave{width:72px;height:14px}
.offair-ornament-line{width:40px;height:2px;background:var(--offair-primary-text);border-radius:2px}
.offair-title{font-weight:600;font-size:26px;line-height:1.3;color:#222;margin:0 0 16px}
.offair-message p{margin:0 0 14px;font-size:16px}
.offair-button{display:inline-block;margin:18px 0 8px;padding:12px 28px;background:var(--offair-primary);color:var(--offair-on-primary);text-decoration:none;border-radius:999px;font-size:15px;letter-spacing:.04em;transition:background .15s ease}
.offair-button:hover,.offair-button:focus{background:var(--offair-primary-hover)}
.offair-button:focus-visible{outline:2px solid var(--offair-primary-text);outline-offset:3px}
.offair-contact{font-size:14px;color:#777;margin:12px 0 0}
.offair-contact a{color:var(--offair-primary-text)}
.offair-meta{font-size:13px;color:#999;margin:20px 0 0}
.offair-notice{font-size:14px;color:#7a4f00;background:#fff6dd;border-radius:8px;padding:10px 14px;margin:20px 0 0;text-align:left}
.offair-detail{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:1.5;color:#333;background:#f4f4f4;border-radius:8px;padding:12px 14px;margin:20px 0 0;text-align:left;white-space:pre-wrap;word-break:break-word}
@media (max-width:420px){.offair-card{padding:36px 20px 28px}.offair-title{font-size:22px}}
CSS;
	$css = strtr(
		$css,
		array(
			'%primary%'    => $primary,
			'%hover%'      => $hover,
			'%text%'       => $text_color,
			'%on%'         => $on_primary,
			'%background%' => $background,
			'%shadow%'     => $shadow,
		)
	);

	$head   = array();
	$head[] = '<meta charset="UTF-8">';
	$head[] = '<meta name="viewport" content="width=device-width, initial-scale=1">';
	$head[] = '<meta name="robots" content="noindex, nofollow">';
	$head[] = $refresh > 0 ? '<meta http-equiv="refresh" content="' . $refresh . '">' : '';
	$head[] = '<title>' . $esc( '' !== $site_name ? $title . ' · ' . $site_name : $title ) . '</title>';
	$head[] = $favicon;
	$head[] = '<style>' . $css . '</style>';

	$card   = array();
	$card[] = $logo;
	$card[] = $show_name ? '<p class="offair-brand">' . $esc( $site_name ) . '</p>' : '';
	$card[] = $ornaments[ $ornament ];
	$card[] = '<h1 class="offair-title">' . $esc( $title ) . '</h1>';
	$card[] = '' !== $paragraphs ? '<div class="offair-message">' . $paragraphs . '</div>' : '';
	$card[] = '' !== $button ? '<a class="offair-button" href="">' . $esc( $button ) . '</a>' : '';
	$card[] = '' !== $contact ? '<p class="offair-contact">' . $contact . '</p>' : '';
	$card[] = '' !== $notice ? '<p class="offair-notice">' . $esc( $notice ) . '</p>' : '';
	$card[] = '' !== $detail ? '<pre class="offair-detail">' . $esc( $detail ) . '</pre>' : '';
	$card[] = '' !== $meta ? '<p class="offair-meta">' . $esc( $meta ) . '</p>' : '';

	// Every value above was escaped with htmlspecialchars(): WordPress escaping functions are not loaded here.
	$head_html = implode( "\n", array_filter( $head, 'strlen' ) );
	$card_html = '<main class="offair-card">' . "\n" . implode( "\n", array_filter( $card, 'strlen' ) ) . "\n" . '</main>';
	$output    = '';

	/*
	 * The theme template gets every value (raw, to escape with the function it
	 * receives), the built-in markup and the stylesheet. If it fails or prints
	 * nothing, the built-in page is shown instead.
	 */
	if ( '' !== $template ) {
		$render = static function ( $offair_template, $offair ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed -- Read by the included template.
			include $offair_template;
		};
		$level  = ob_get_level();

		ob_start();
		try {
			$render(
				$template,
				array(
					'screen'       => $screen,
					'status'       => $status,
					'lang'         => $lang,
					'site_name'    => $site_name,
					'show_name'    => $show_name,
					'title'        => $title,
					'paragraphs'   => $paragraph_list,
					'button'       => $button,
					'contact'      => $contact_parts,
					'notice'       => $notice,
					'detail'       => $detail,
					'meta'         => $meta,
					'refresh'      => $refresh,
					'logo'         => $logo_data,
					'favicon'      => $favicon_data,
					'colors'       => array(
						'primary'       => $primary,
						'primary_hover' => $hover,
						'primary_text'  => $text_color,
						'on_primary'    => $on_primary,
						'background'    => $background,
					),
					'heading_font' => $font,
					'ornament'     => $ornament,
					'css'          => $css,
					'head'         => $head_html,
					'card'         => $card_html,
					'escape'       => $esc,
				)
			);
			while ( ob_get_level() > $level ) {
				$output = (string) ob_get_clean() . $output;
			}
		} catch ( Throwable $exception ) {
			while ( ob_get_level() > $level ) {
				ob_end_clean();
			}
			$output = '';
		}
	}

	if ( '' === trim( $output ) ) {
		$output = implode(
			"\n",
			array(
				'<!DOCTYPE html>',
				'<html lang="' . $esc( $lang ) . '">',
				'<head>',
				$head_html,
				'</head>',
				'<body class="offair-font-' . $font . ' offair-screen-' . $screen . '">',
				$card_html,
				'</body>',
				'</html>',
			)
		) . "\n";
	}

	// Built-in markup escaped above, or the output of a template of the active theme.
	echo $output; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped

	/*
	 * History and alert run once the page is out, so that they never delay it
	 * or break it. Errors are silenced for the same reason: a folder that
	 * cannot be written must not print anything on this page.
	 */
	if ( defined( 'OFFAIR_PREVIEW' ) || '' === $private_dir ) {
		return;
	}

	$now_ts = time();
	$seen   = $private_dir . '/seen-' . $screen;
	$last   = @filemtime( $seen ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged

	// One line a minute per page at most, however many visitors come. Nothing about them is recorded.
	if ( false === $last || $last <= $now_ts - 60 ) {
		@touch( $seen ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_system_operations_touch
		@file_put_contents( $private_dir . '/events.log', $now_ts . ' ' . $screen . ' ' . $status . "\n", FILE_APPEND | LOCK_EX ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	$alert = isset( $private['alert'] ) && is_array( $private['alert'] ) ? $private['alert'] : array();

	if ( 'db' !== $screen || ! function_exists( 'mail' ) || ! isset( $alert['to'], $alert['subject'], $alert['body'], $alert['headers'] ) || ! is_string( $alert['to'] ) || ! filter_var( $alert['to'], FILTER_VALIDATE_EMAIL ) ) {
		return;
	}

	// One alert an hour at most. The lock keeps two visitors arriving together from both sending it.
	$send   = false;
	$handle = @fopen( $private_dir . '/alert-db', 'c+' ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_system_operations_fopen

	if ( false !== $handle ) {
		if ( flock( $handle, LOCK_EX | LOCK_NB ) ) {
			$sent_at = (int) stream_get_contents( $handle );

			if ( $sent_at <= $now_ts - 3600 ) {
				ftruncate( $handle, 0 );
				rewind( $handle );
				fwrite( $handle, (string) $now_ts ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fwrite
				fflush( $handle );
				$send = true;
			}

			flock( $handle, LOCK_UN );
		}
		fclose( $handle ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose
	}

	if ( ! $send ) {
		return;
	}

	// Numeric date and time: month names cannot be translated here.
	$when = gmdate( 'Y-m-d H:i' ) . ' (UTC)';
	try {
		$zone = new DateTimeZone( $str( isset( $data['timezone'] ) ? $data['timezone'] : null, 'UTC' ) );
		$when = ( new DateTime( 'now', $zone ) )->format( 'Y-m-d H:i' ) . ' (' . $zone->getName() . ')';
	} catch ( Exception $exception ) {
		$when = gmdate( 'Y-m-d H:i' ) . ' (UTC)';
	}

	// The visitor already has the page: the connection is closed before talking to the mail server.
	if ( function_exists( 'fastcgi_finish_request' ) ) {
		fastcgi_finish_request();
	}

	// WordPress cannot run while the database is down, so wp_mail() is not available.
	@mail( $alert['to'], (string) $alert['subject'], str_replace( '{time}', $when, (string) $alert['body'] ), (string) $alert['headers'] ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
} )( isset( $error ) ? $error : null, isset( $handled ) ? $handled : null );
