<?php
/**
 * Offair drop-in.
 *
 * WordPress loads this file by itself, before any plugin or theme, in three
 * situations: when the database is unreachable (wp-content/db-error.php),
 * while it installs updates (wp-content/maintenance.php) and after a fatal
 * PHP error (wp-content/php-error.php). WordPress functions are not
 * available at that point, so this file only uses plain PHP.
 *
 * The Offair plugin copies this file unchanged under those
 * three names. The page content comes from the JSON file the plugin saves in
 * the uploads folder (offair/pages.json). When that file is
 * missing, a neutral English page is shown instead.
 *
 * Do not edit this file: the plugin replaces it when it is updated and
 * removes it when it is deactivated or uninstalled.
 *
 * @package Offair
 */

defined( 'ABSPATH' ) || exit;

/*
 * Everything runs inside a closure so that no global variable or function is
 * declared. WordPress includes this file from inside one of its own functions,
 * and php-error.php receives $error and $handled from that scope.
 */
( static function ( $error, $handled ) {
	$screens = array(
		'db-error.php'    => 'db',
		'maintenance.php' => 'maintenance',
		'php-error.php'   => 'php',
	);
	$file    = basename( __FILE__ );
	$screen  = isset( $screens[ $file ] ) ? $screens[ $file ] : 'db';

	// The plugin preview and WP-CLI render a given page from the plugin folder.
	if ( defined( 'OFFAIR_PREVIEW' ) && in_array( OFFAIR_PREVIEW, $screens, true ) ) {
		$screen = OFFAIR_PREVIEW;
	}

	$esc = static function ( $value ) {
		return htmlspecialchars( (string) $value, ENT_QUOTES, 'UTF-8' );
	};
	$str = static function ( $value, $fallback = '' ) {
		return is_string( $value ) ? $value : $fallback;
	};
	$num = static function ( $value, $min, $max, $fallback ) {
		return is_int( $value ) && $value >= $min && $value <= $max ? $value : $fallback;
	};
	$hex = static function ( $value, $fallback ) {
		return is_string( $value ) && preg_match( '/^#[0-9a-f]{6}$/i', $value ) ? strtolower( $value ) : $fallback;
	};

	// Neutral page used when the plugin data cannot be read.
	$fallback_screens = array(
		'db'          => array(
			'title'      => "We'll be right back",
			'paragraphs' => array( 'Our site is taking a short break because of a technical problem. It usually comes back within a few minutes.' ),
			'meta'       => 'Incident recorded at {time} (UTC). Database temporarily unavailable (HTTP 503).',
		),
		'maintenance' => array(
			'title'      => 'Back in a minute',
			'paragraphs' => array( 'We are installing an update. The site will be back in a moment.' ),
			'meta'       => 'Incident recorded at {time} (UTC). Scheduled maintenance in progress (HTTP 503).',
		),
		'php'         => array(
			'title'      => 'Something went wrong',
			'paragraphs' => array( 'A technical error prevents us from displaying this page right now. Please try again in a few minutes.' ),
			'meta'       => 'Incident recorded at {time} (UTC). Technical error (HTTP 503).',
			'refresh'    => 0,
		),
	);
	$page_defaults    = array(
		'button'      => 'Try again',
		'refresh'     => 60,
		'retry_after' => 300,
		'status'      => 503,
		'notice'      => '',
	);

	/*
	 * Same location as wp_upload_dir() for the main site. The database may be
	 * down, so the path is worked out from the constants WordPress defines in
	 * wp-config.php and wp-settings.php.
	 */
	$content_dir = defined( 'WP_CONTENT_DIR' ) ? WP_CONTENT_DIR : ABSPATH . 'wp-content';
	$uploads_dir = defined( 'UPLOADS' ) ? ABSPATH . UPLOADS : $content_dir . '/uploads';
	$data_file   = rtrim( $uploads_dir, '/\\' ) . '/offair/pages.json';
	$data        = array();

	/*
	 * The settings page previews settings that are not saved yet: it hands the
	 * content over directly, so that nothing on the site is written or changed.
	 */
	if ( defined( 'OFFAIR_PREVIEW_DATA' ) ) {
		$json = json_decode( (string) OFFAIR_PREVIEW_DATA, true );
		$data = is_array( $json ) ? $json : array();
	} elseif ( is_readable( $data_file ) ) {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local file, WordPress is not loaded.
		$raw  = file_get_contents( $data_file );
		$json = is_string( $raw ) ? json_decode( $raw, true ) : null;
		$data = is_array( $json ) ? $json : array();
	}

	/*
	 * On a network, each site has its own page. WordPress has not worked out
	 * which site is asked for yet, so the address is compared with the list
	 * of sites the plugin saves: same domain, longest matching path.
	 */
	$site_id  = 0;
	$data_dir = dirname( $data_file );

	if ( defined( 'OFFAIR_PREVIEW_SITE' ) ) {
		$site_id = (int) OFFAIR_PREVIEW_SITE;
	} elseif ( defined( 'MULTISITE' ) && MULTISITE && is_readable( $data_dir . '/sites.json' ) ) {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local file, WordPress is not loaded.
		$raw   = file_get_contents( $data_dir . '/sites.json' );
		$map   = is_string( $raw ) ? json_decode( $raw, true ) : null;
		$host  = isset( $_SERVER['HTTP_HOST'] ) ? strtolower( (string) $_SERVER['HTTP_HOST'] ) : ''; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- Only compared with the list of sites, WordPress is not loaded.
		$hosts = array( $host, (string) preg_replace( '/:\d+$/', '', $host ) );
		$path  = isset( $_SERVER['REQUEST_URI'] ) ? (string) parse_url( (string) $_SERVER['REQUEST_URI'], PHP_URL_PATH ) : '/'; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput, WordPress.WP.AlternativeFunctions.parse_url_parse_url -- Only compared with the list of sites, WordPress is not loaded.
		$path  = rtrim( $path, '/' ) . '/';
		$best  = -1;

		foreach ( is_array( $map ) ? $map : array() as $site ) {
			if ( ! isset( $site['id'], $site['domain'], $site['path'] ) || ! is_string( $site['domain'] ) || ! is_string( $site['path'] ) ) {
				continue;
			}
			if ( in_array( $site['domain'], $hosts, true ) && 0 === strpos( $path, $site['path'] ) && strlen( $site['path'] ) > $best ) {
				$best    = strlen( $site['path'] );
				$site_id = (int) $site['id'];
			}
		}
	}

	// The main site has no file of its own: its content is pages.json.
	if ( ! defined( 'OFFAIR_PREVIEW_DATA' ) && $site_id > 0 && is_readable( $data_dir . '/sites/' . $site_id . '.json' ) ) {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local file, WordPress is not loaded.
		$raw  = file_get_contents( $data_dir . '/sites/' . $site_id . '.json' );
		$json = is_string( $raw ) ? json_decode( $raw, true ) : null;
		$data = is_array( $json ) ? $json : $data;
	}

	/*
	 * Private folder, next to the data file: its name cannot be guessed, so
	 * it is found by its prefix. It holds the alert settings, the folders of
	 * the active theme and the history of the pages shown.
	 */
	$private_dir = '';
	$private     = array();
	$found       = glob( dirname( $data_file ) . '/private-*', defined( 'GLOB_ONLYDIR' ) ? GLOB_ONLYDIR : 0 );

	if ( is_array( $found ) && isset( $found[0] ) && is_dir( $found[0] ) ) {
		$private_dir = $found[0];

		if ( is_readable( $private_dir . '/private.json' ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local file, WordPress is not loaded.
			$raw     = file_get_contents( $private_dir . '/private.json' );
			$json    = is_string( $raw ) ? json_decode( $raw, true ) : null;
			$private = is_array( $json ) ? $json : array();
		}

		// On a network, the templates come from the theme of the site asked for.
		if ( $site_id > 0 && is_readable( $private_dir . '/sites/' . $site_id . '.json' ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local file, WordPress is not loaded.
			$raw  = file_get_contents( $private_dir . '/sites/' . $site_id . '.json' );
			$json = is_string( $raw ) ? json_decode( $raw, true ) : null;

			if ( is_array( $json ) && isset( $json['themes'] ) ) {
				$private['themes'] = $json['themes'];
			}
		}
	}

	/*
	 * A template named after this file, in an offair folder of the active
	 * theme or of its parent, replaces the built-in page. The path is checked
	 * against wp-content/themes, never against the data files, which sit in a
	 * folder the web server can write to.
	 */
	$template = '';
	$themes   = realpath( $content_dir . '/themes' );
	$files    = array_flip( $screens );

	foreach ( false !== $themes && isset( $private['themes'] ) && is_array( $private['themes'] ) ? $private['themes'] : array() as $theme_dir ) {
		$candidate = is_string( $theme_dir ) ? realpath( $theme_dir . '/offair/' . $files[ $screen ] ) : false;

		if ( false !== $candidate && 0 === strpos( $candidate, $themes . DIRECTORY_SEPARATOR ) && is_readable( $candidate ) ) {
			$template = $candidate;
			break;
		}
	}

	$page = array_merge( $page_defaults, $fallback_screens[ $screen ] );
	if ( isset( $data['screens'][ $screen ] ) && is_array( $data['screens'][ $screen ] ) ) {
		$page = array_merge( $page, $data['screens'][ $screen ] );
	}

	$status      = 500 === $num( $page['status'], 500, 503, 503 ) ? 500 : 503;
	$retry_after = $num( $page['retry_after'], 0, 86400, 300 );
	$refresh     = $num( $page['refresh'], 0, 3600, 60 );

	// A preview sits in a frame of the settings page: it must not reload itself.
	if ( defined( 'OFFAIR_PREVIEW' ) ) {
		$refresh = 0;
	}

	// A fatal error may leave partial output behind: start from a clean page.
	if ( 'php' === $screen ) {
		while ( ob_get_level() > 0 && ob_end_clean() ) {
			continue;
		}
	}

	if ( ! headers_sent() ) {
		// Same status line as WordPress builds in status_header(), from a fixed list of protocols.
		$protocols = array( 'HTTP/1.1', 'HTTP/2', 'HTTP/2.0', 'HTTP/3' );
		$protocol  = isset( $_SERVER['SERVER_PROTOCOL'] ) && in_array( $_SERVER['SERVER_PROTOCOL'], $protocols, true ) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.0'; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- Compared against a fixed list, WordPress is not loaded.
		header( $protocol . ' ' . ( 503 === $status ? '503 Service Unavailable' : '500 Internal Server Error' ), true, $status );
		if ( 503 === $status && $retry_after > 0 ) {
			header( 'Retry-After: ' . $retry_after );
		}
		header( 'Content-Type: text/html; charset=UTF-8' );
		header( 'Cache-Control: no-store, no-cache, must-revalidate, max-age=0' );
		header( 'Pragma: no-cache' );
		header( 'Expires: Wed, 11 Jan 1984 05:00:00 GMT' );
		header( 'X-LiteSpeed-Cache-Control: no-cache' );
		header( 'X-Robots-Tag: noindex, nofollow' );
	}

	// Local time of the incident, in the timezone of the site.
	$time = gmdate( 'H:i' ) . ' UTC';
	try {
		$now  = new DateTime( 'now', new DateTimeZone( $str( isset( $data['timezone'] ) ? $data['timezone'] : null, 'UTC' ) ) );
		$time = $now->format( $str( isset( $data['time_format'] ) ? $data['time_format'] : null, 'H:i' ) );
	} catch ( Exception $exception ) {
		$time = gmdate( 'H:i' ) . ' UTC';
	}

	// Technical details, only where WordPress itself would print errors.
	$detail = '';
	if ( 'php' === $screen && defined( 'WP_DEBUG' ) && WP_DEBUG && defined( 'WP_DEBUG_DISPLAY' ) && WP_DEBUG_DISPLAY && is_array( $error ) ) {
		$detail = trim( $str( isset( $error['message'] ) ? $error['message'] : null ) );
		if ( isset( $error['file'] ) ) {
			$detail .= "\n" . $str( $error['file'] ) . ( isset( $error['line'] ) ? ':' . (int) $error['line'] : '' );
		}
		$detail = trim( $detail );
	}

	// An administrator in recovery mode is told what just happened.
	$notice = '';
	if ( 'php' === $screen && true === $handled && function_exists( 'wp_is_recovery_mode' ) && wp_is_recovery_mode() ) {
		$notice = $str( $page['notice'] );
	}

	$colors     = isset( $data['colors'] ) && is_array( $data['colors'] ) ? $data['colors'] : array();
	$primary    = $hex( isset( $colors['primary'] ) ? $colors['primary'] : null, '#334155' );
	$hover      = $hex( isset( $colors['primary_hover'] ) ? $colors['primary_hover'] : null, $primary );
	$text_color = $hex( isset( $colors['primary_text'] ) ? $colors['primary_text'] : null, $primary );
	$text_dark  = $hex( isset( $colors['primary_dark'] ) ? $colors['primary_dark'] : null, '#a9b4c2' );
	$on_primary = $hex( isset( $colors['on_primary'] ) ? $colors['on_primary'] : null, '#ffffff' );
	$background = $hex( isset( $colors['background'] ) ? $colors['background'] : null, '#f5f4f0' );
	$rgb        = sscanf( $primary, '#%02x%02x%02x' );
	$shadow     = sprintf( 'rgba(%d, %d, %d, 0.12)', $rgb[0], $rgb[1], $rgb[2] );

	$lang      = $str( isset( $data['lang'] ) ? $data['lang'] : null, 'en' );
	$lang      = preg_match( '/^[a-z]{2,3}(-[a-z0-9]{2,8})*$/i', $lang ) ? $lang : 'en';
	$site_name = $str( isset( $data['site_name'] ) ? $data['site_name'] : null );
	$show_name = ! empty( $data['show_name'] ) && '' !== $site_name;
	$font      = isset( $data['heading_font'] ) && 'sans' === $data['heading_font'] ? 'sans' : 'serif';
	$ornament  = isset( $data['ornament'] ) && in_array( $data['ornament'], array( 'wave', 'line', 'none' ), true ) ? $data['ornament'] : 'line';
	$layout    = isset( $data['layout'] ) && in_array( $data['layout'], array( 'card', 'minimal', 'split', 'banner' ), true ) ? $data['layout'] : 'card';
	$scheme    = isset( $data['color_scheme'] ) && in_array( $data['color_scheme'], array( 'auto', 'light', 'dark' ), true ) ? $data['color_scheme'] : 'auto';
	$panel     = in_array( $layout, array( 'split', 'banner' ), true );
	$title     = $str( $page['title'] );
	$button    = $str( $page['button'] );
	$meta      = str_replace( '{time}', $time, $str( $page['meta'] ) );
	$image     = '#^data:image/(?:png|jpeg|gif|webp|svg\+xml|x-icon|vnd\.microsoft\.icon);base64,[a-z0-9+/=]+$#i';

	// A logo is kept only when it is an embedded image the page can show.
	$logo_of  = static function ( $value ) use ( $image, $num ) {
		if ( ! isset( $value['src'] ) || ! is_string( $value['src'] ) || ! preg_match( $image, $value['src'] ) ) {
			return null;
		}

		return array(
			'src'    => $value['src'],
			'width'  => $num( isset( $value['width'] ) ? $value['width'] : null, 1, 2000, 0 ),
			'height' => $num( isset( $value['height'] ) ? $value['height'] : null, 1, 2000, 0 ),
		);
	};
	$logo_img = static function ( $value, $classes ) use ( $esc, $site_name ) {
		$size = $value['width'] && $value['height'] ? ' width="' . $value['width'] . '" height="' . $value['height'] . '"' : '';

		return '<img class="offair-logo' . ( '' !== $classes ? ' ' . $classes : '' ) . '" src="' . $esc( $value['src'] ) . '" alt="' . $esc( $site_name ) . '"' . $size . '>';
	};

	// Relative luminance, as WCAG 2 defines it: a panel darker than 0.179 carries light text better than dark text.
	$lum = 0;
	foreach ( array( 0.2126, 0.7152, 0.0722 ) as $index => $weight ) {
		$channel = $rgb[ $index ] / 255;
		$lum    += $weight * ( $channel <= 0.03928 ? $channel / 12.92 : pow( ( $channel + 0.055 ) / 1.055, 2.4 ) );
	}

	$logo_data = $logo_of( isset( $data['logo'] ) ? $data['logo'] : null );
	$logo_dark = $logo_of( isset( $data['logo_dark'] ) ? $data['logo_dark'] : null );
	$logo      = '';

	/*
	 * The logo for dark backgrounds, when there is one, takes the place of the
	 * logo on the colored panel of the two-column and banner layouts when that
	 * color is dark, and in dark mode. Without it, the logo stays as it is.
	 */
	if ( null !== $logo_data ) {
		if ( null === $logo_dark || ( 'light' === $scheme && ( ! $panel || $lum >= 0.179 ) ) ) {
			$logo = $logo_img( $logo_data, '' );
		} elseif ( $panel ) {
			$logo = $lum < 0.179 ? $logo_img( $logo_dark, '' ) : $logo_img( $logo_data, '' );
		} elseif ( 'dark' === $scheme ) {
			$logo = $logo_img( $logo_dark, '' );
		} else {
			$logo = $logo_img( $logo_data, 'offair-logo-onlight' ) . $logo_img( $logo_dark, 'offair-logo-ondark' );
		}
	}

	$favicon      = '';
	$favicon_data = '';
	if ( isset( $data['favicon'] ) && is_string( $data['favicon'] ) && preg_match( $image, $data['favicon'] ) ) {
		$favicon      = '<link rel="icon" href="' . $esc( $data['favicon'] ) . '">';
		$favicon_data = $data['favicon'];
	}

	$paragraphs     = '';
	$paragraph_list = array();
	foreach ( is_array( $page['paragraphs'] ) ? $page['paragraphs'] : array() as $paragraph ) {
		if ( is_string( $paragraph ) && '' !== trim( $paragraph ) ) {
			$paragraphs      .= '<p>' . nl2br( $esc( trim( $paragraph ) ) ) . '</p>';
			$paragraph_list[] = trim( $paragraph );
		}
	}

	$contact       = '';
	$contact_parts = array();
	foreach ( isset( $data['contact'] ) && is_array( $data['contact'] ) ? $data['contact'] : array() as $part ) {
		if ( ! isset( $part['text'] ) || ! is_string( $part['text'] ) ) {
			continue;
		}
		if ( isset( $part['href'] ) && is_string( $part['href'] ) && preg_match( '#^(?:https?://|mailto:)#i', $part['href'] ) ) {
			$contact        .= '<a href="' . $esc( $part['href'] ) . '">' . $esc( $part['text'] ) . '</a>';
			$contact_parts[] = array(
				'text' => $part['text'],
				'href' => $part['href'],
			);
		} else {
			$contact        .= $esc( $part['text'] );
			$contact_parts[] = array( 'text' => $part['text'] );
		}
	}

	$ornaments = array(
		'wave' => '<svg class="offair-ornament offair-ornament-wave" viewBox="0 0 72 14" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M2 8c6-8 12-8 18 0s12 8 18 0 12-8 18 0 12 8 14 0"/></svg>',
		'line' => '<span class="offair-ornament offair-ornament-line" aria-hidden="true"></span>',
		'none' => '',
	);

	/*
	 * Styles are printed inline on purpose: this page is shown while
	 * WordPress cannot load, and during updates, when the plugin folder may
	 * be in the middle of being replaced. A stylesheet could not be enqueued
	 * and a link to one could return an error.
	 *
	 * Colors that change in dark mode are custom properties of the body. The
	 * dark values apply with the dark scheme, and with the automatic scheme
	 * when the device of the visitor asks for dark.
	 */
	$css = <<<'CSS'
:root{--offair-primary:%primary%;--offair-primary-hover:%hover%;--offair-on-primary:%on%;--offair-accent-light:%text%;--offair-accent-dark:%text_dark%;--offair-background:%background%;--offair-shadow-light:%shadow%}
*,*::before,*::after{box-sizing:border-box}
html,body{margin:0;padding:0;min-height:100%}
body{--offair-bg:var(--offair-background);--offair-glow:rgba(255,255,255,.85);--offair-surface:#fff;--offair-text:#555;--offair-title:#222;--offair-soft:#777;--offair-muted:#999;--offair-accent:var(--offair-accent-light);--offair-code-bg:#f4f4f4;--offair-code:#333;--offair-notice-bg:#fff6dd;--offair-notice:#7a4f00;--offair-shadow:var(--offair-shadow-light);font-family:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;color:var(--offair-text);background-color:var(--offair-bg);background-image:linear-gradient(180deg,var(--offair-glow) 0%,rgba(255,255,255,0) 100%);display:flex;align-items:center;justify-content:center;min-height:100vh;padding:24px 16px;line-height:1.6;-webkit-font-smoothing:antialiased}
.offair-scheme-dark{%dark%}
.offair-font-serif .offair-brand,.offair-font-serif .offair-title{font-family:Georgia,"Iowan Old Style","Palatino Linotype",Palatino,"Book Antiqua","Times New Roman",serif}
.offair-font-sans .offair-brand,.offair-font-sans .offair-title{font-family:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif}
.offair-page{width:100%}
.offair-layout-card .offair-page{background:var(--offair-surface);max-width:520px;padding:48px 32px 36px;border-radius:16px;box-shadow:0 12px 40px var(--offair-shadow);text-align:center}
.offair-layout-minimal .offair-page{max-width:560px;padding:16px 4px;text-align:center}
.offair-layout-split .offair-page{display:grid;grid-template-columns:minmax(200px,5fr) 7fr;max-width:860px;background:var(--offair-surface);border-radius:16px;overflow:hidden;box-shadow:0 12px 40px var(--offair-shadow)}
.offair-layout-split.offair-no-head .offair-page{grid-template-columns:1fr;max-width:560px}
.offair-layout-split .offair-head{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:40px 28px;text-align:center}
.offair-layout-split .offair-content{padding:48px 40px 40px;text-align:left}
.offair-layout-split .offair-ornament{margin-left:0}
.offair-layout-banner{display:block;padding:0}
.offair-layout-banner .offair-head{display:flex;flex-wrap:wrap;align-items:center;justify-content:center;gap:12px 18px;padding:22px 16px}
.offair-layout-banner .offair-content{max-width:600px;margin:0 auto;padding:56px 20px 40px;text-align:center}
.offair-layout-split .offair-head,.offair-layout-banner .offair-head{background:var(--offair-primary);color:var(--offair-on-primary)}
.offair-logo{display:block;margin:0 auto 20px;width:auto;height:auto;max-width:160px;max-height:120px}
.offair-layout-split .offair-logo{max-width:180px;max-height:140px;margin-bottom:16px}
.offair-layout-banner .offair-logo{margin:0;max-width:200px;max-height:56px}
.offair-logo-ondark{display:none}
.offair-brand{font-size:15px;letter-spacing:.18em;text-transform:uppercase;color:var(--offair-accent);margin:0 0 24px}
.offair-layout-split .offair-brand,.offair-layout-banner .offair-brand{color:var(--offair-on-primary);margin:0}
.offair-ornament{display:block;margin:0 auto 24px;color:var(--offair-accent)}
.offair-ornament-wave{width:72px;height:14px}
.offair-ornament-line{width:40px;height:2px;background:var(--offair-accent);border-radius:2px}
.offair-title{font-weight:600;font-size:26px;line-height:1.3;color:var(--offair-title);margin:0 0 16px}
.offair-message p{margin:0 0 14px;font-size:16px}
.offair-button{display:inline-block;margin:18px 0 8px;padding:12px 28px;background:var(--offair-primary);color:var(--offair-on-primary);text-decoration:none;border-radius:999px;font-size:15px;letter-spacing:.04em;transition:background .15s ease}
.offair-button:hover,.offair-button:focus{background:var(--offair-primary-hover)}
.offair-button:focus-visible{outline:2px solid var(--offair-accent);outline-offset:3px}
.offair-contact{font-size:14px;color:var(--offair-soft);margin:12px 0 0}
.offair-contact a{color:var(--offair-accent)}
.offair-meta{font-size:13px;color:var(--offair-muted);margin:20px 0 0}
.offair-notice{font-size:14px;color:var(--offair-notice);background:var(--offair-notice-bg);border-radius:8px;padding:10px 14px;margin:20px 0 0;text-align:left}
.offair-detail{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:1.5;color:var(--offair-code);background:var(--offair-code-bg);border-radius:8px;padding:12px 14px;margin:20px 0 0;text-align:left;white-space:pre-wrap;word-break:break-word}
@media (prefers-color-scheme:dark){.offair-scheme-auto{%dark%}.offair-logo-onlight{display:none}.offair-logo-ondark{display:block}}
@media (max-width:700px){.offair-layout-split .offair-page{grid-template-columns:1fr}.offair-layout-split .offair-head{padding:28px 20px}.offair-layout-split .offair-content{padding:32px 24px 28px;text-align:center}.offair-layout-split .offair-ornament{margin-left:auto}}
@media (max-width:420px){.offair-layout-card .offair-page{padding:36px 20px 28px}.offair-title{font-size:22px}}
CSS;
	$css = strtr(
		$css,
		array(
			'%dark%'       => '--offair-bg:#131519;--offair-glow:rgba(255,255,255,.04);--offair-surface:#1c1f24;--offair-text:#c9cdd3;--offair-title:#f2f3f5;--offair-soft:#a4a9b1;--offair-muted:#8a9099;--offair-accent:var(--offair-accent-dark);--offair-code-bg:#121418;--offair-code:#d9dce1;--offair-notice-bg:#3a2f12;--offair-notice:#ffd98a;--offair-shadow:rgba(0,0,0,.45)',
			'%primary%'    => $primary,
			'%hover%'      => $hover,
			'%text%'       => $text_color,
			'%text_dark%'  => $text_dark,
			'%on%'         => $on_primary,
			'%background%' => $background,
			'%shadow%'     => $shadow,
		)
	);

	$head   = array();
	$head[] = '<meta charset="UTF-8">';
	$head[] = '<meta name="viewport" content="width=device-width, initial-scale=1">';
	$head[] = '<meta name="robots" content="noindex, nofollow">';
	$head[] = '<meta name="color-scheme" content="' . ( 'auto' === $scheme ? 'light dark' : $scheme ) . '">';
	$head[] = $refresh > 0 ? '<meta http-equiv="refresh" content="' . $refresh . '">' : '';
	$head[] = '<title>' . $esc( '' !== $site_name ? $title . ' · ' . $site_name : $title ) . '</title>';
	$head[] = $favicon;
	$head[] = '<style>' . $css . '</style>';

	// The same markup serves every layout: the stylesheet arranges the header and the content.
	$brand   = $show_name ? '<p class="offair-brand">' . $esc( $site_name ) . '</p>' : '';
	$top     = '' !== $logo || '' !== $brand ? '<header class="offair-head">' . "\n" . implode( "\n", array_filter( array( $logo, $brand ), 'strlen' ) ) . "\n" . '</header>' : '';
	$content = array(
		$ornaments[ $ornament ],
		'<h1 class="offair-title">' . $esc( $title ) . '</h1>',
		'' !== $paragraphs ? '<div class="offair-message">' . $paragraphs . '</div>' : '',
		'' !== $button ? '<a class="offair-button" href="">' . $esc( $button ) . '</a>' : '',
		'' !== $contact ? '<p class="offair-contact">' . $contact . '</p>' : '',
		'' !== $notice ? '<p class="offair-notice">' . $esc( $notice ) . '</p>' : '',
		'' !== $detail ? '<pre class="offair-detail">' . $esc( $detail ) . '</pre>' : '',
		'' !== $meta ? '<p class="offair-meta">' . $esc( $meta ) . '</p>' : '',
	);

	// Every value above was escaped with htmlspecialchars(): WordPress escaping functions are not loaded here.
	$head_html  = implode( "\n", array_filter( $head, 'strlen' ) );
	$main_html  = '<main class="offair-page">' . "\n" . ( '' !== $top ? $top . "\n" : '' ) . '<div class="offair-content">' . "\n" . implode( "\n", array_filter( $content, 'strlen' ) ) . "\n" . '</div>' . "\n" . '</main>';
	$body_class = 'offair-font-' . $font . ' offair-screen-' . $screen . ' offair-layout-' . $layout . ' offair-scheme-' . $scheme . ( '' === $top ? ' offair-no-head' : '' );
	$output     = '';

	/*
	 * The theme template gets every value (raw, to escape with the function it
	 * receives), the built-in markup and the stylesheet. If it fails or prints
	 * nothing, the built-in page is shown instead.
	 */
	if ( '' !== $template ) {
		$render = static function ( $offair_template, $offair ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed -- Read by the included template.
			include $offair_template;
		};
		$level  = ob_get_level();

		ob_start();
		try {
			$render(
				$template,
				array(
					'screen'       => $screen,
					'status'       => $status,
					'lang'         => $lang,
					'site_name'    => $site_name,
					'show_name'    => $show_name,
					'title'        => $title,
					'paragraphs'   => $paragraph_list,
					'button'       => $button,
					'contact'      => $contact_parts,
					'notice'       => $notice,
					'detail'       => $detail,
					'meta'         => $meta,
					'refresh'      => $refresh,
					'logo'         => $logo_data,
					'logo_dark'    => $logo_dark,
					'favicon'      => $favicon_data,
					'colors'       => array(
						'primary'       => $primary,
						'primary_hover' => $hover,
						'primary_text'  => $text_color,
						'primary_dark'  => $text_dark,
						'on_primary'    => $on_primary,
						'background'    => $background,
					),
					'heading_font' => $font,
					'ornament'     => $ornament,
					'layout'       => $layout,
					'color_scheme' => $scheme,
					'css'          => $css,
					'head'         => $head_html,
					'main'         => $main_html,
					'body_class'   => $body_class,
					'escape'       => $esc,
				)
			);
			while ( ob_get_level() > $level ) {
				$output = (string) ob_get_clean() . $output;
			}
		} catch ( Throwable $exception ) {
			while ( ob_get_level() > $level ) {
				ob_end_clean();
			}
			$output = '';
		}
	}

	if ( '' === trim( $output ) ) {
		$output = implode(
			"\n",
			array(
				'<!DOCTYPE html>',
				'<html lang="' . $esc( $lang ) . '">',
				'<head>',
				$head_html,
				'</head>',
				'<body class="' . $body_class . '">',
				$main_html,
				'</body>',
				'</html>',
			)
		) . "\n";
	}

	// Built-in markup escaped above, or the output of a template of the active theme.
	echo $output; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped

	/*
	 * History and alert run once the page is out, so that they never delay it
	 * or break it. Errors are silenced for the same reason: a folder that
	 * cannot be written must not print anything on this page.
	 */
	if ( defined( 'OFFAIR_PREVIEW' ) || '' === $private_dir ) {
		return;
	}

	$now_ts = time();
	$seen   = $private_dir . '/seen-' . $screen;
	$last   = @filemtime( $seen ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged

	// One line a minute per page at most, however many visitors come. Nothing about them is recorded.
	if ( false === $last || $last <= $now_ts - 60 ) {
		@touch( $seen ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_system_operations_touch
		@file_put_contents( $private_dir . '/events.log', $now_ts . ' ' . $screen . ' ' . $status . "\n", FILE_APPEND | LOCK_EX ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	$alert = isset( $private['alert'] ) && is_array( $private['alert'] ) ? $private['alert'] : array();

	if ( 'db' !== $screen || ! function_exists( 'mail' ) || ! isset( $alert['to'], $alert['subject'], $alert['body'], $alert['headers'] ) || ! is_string( $alert['to'] ) || ! filter_var( $alert['to'], FILTER_VALIDATE_EMAIL ) ) {
		return;
	}

	// One alert an hour at most. The lock keeps two visitors arriving together from both sending it.
	$send   = false;
	$handle = @fopen( $private_dir . '/alert-db', 'c+' ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_system_operations_fopen

	if ( false !== $handle ) {
		if ( flock( $handle, LOCK_EX | LOCK_NB ) ) {
			$sent_at = (int) stream_get_contents( $handle );

			if ( $sent_at <= $now_ts - 3600 ) {
				ftruncate( $handle, 0 );
				rewind( $handle );
				fwrite( $handle, (string) $now_ts ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fwrite
				fflush( $handle );
				$send = true;
			}

			flock( $handle, LOCK_UN );
		}
		fclose( $handle ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose
	}

	if ( ! $send ) {
		return;
	}

	// Numeric date and time: month names cannot be translated here.
	$when = gmdate( 'Y-m-d H:i' ) . ' (UTC)';
	try {
		$zone = new DateTimeZone( $str( isset( $data['timezone'] ) ? $data['timezone'] : null, 'UTC' ) );
		$when = ( new DateTime( 'now', $zone ) )->format( 'Y-m-d H:i' ) . ' (' . $zone->getName() . ')';
	} catch ( Exception $exception ) {
		$when = gmdate( 'Y-m-d H:i' ) . ' (UTC)';
	}

	// The visitor already has the page: the connection is closed before talking to the mail server.
	if ( function_exists( 'fastcgi_finish_request' ) ) {
		fastcgi_finish_request();
	}

	// WordPress cannot run while the database is down, so wp_mail() is not available.
	@mail( $alert['to'], (string) $alert['subject'], str_replace( '{time}', $when, (string) $alert['body'] ), (string) $alert['headers'] ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
} )( isset( $error ) ? $error : null, isset( $handled ) ? $handled : null );
